<?php
/****В этом хуке мы описываем используемые блоки.*****/
function rss_mod_block_info()
{
    $blocks['rss_mod'] = array(
        'info'  => t('RSS Feeds'),
        'cache' => DRUPAL_CACHE_PER_ROLE, // по умолчанию
    );

    return $blocks;
}
/**********Далее описываем hook_menu():*********/
function rss_mod_menu()
{

    $items = array();

    $items['admin/config/content/rss_mod'] = array(
        'title'            => 'RSS Module',
        'description'      => 'Configure the RSS feeds list.',
        'page callback'    => 'rss_list',
        'access arguments' => array('administer site configuration'),
    );
    $items['admin/config/content/rss_mod/list'] = array(
        'title'  => 'RSS feeds list',
        'type'   => MENU_DEFAULT_LOCAL_TASK,
        'weight' => 1,
    );

    // modrss add form
    $items['admin/config/content/rss_mod/add'] = array(
        'title'            => 'Add modrss',
        'page callback'    => 'drupal_get_form',
        'page arguments'   => array('rss_mod_form'),
        'access arguments' => array('administer site configuration'),
        'type'             => MENU_LOCAL_TASK,
        'weight'           => 2,
    );

    // modrss edit form
    $items['admin/config/content/rss_mod/%modrss/edit'] = array(
        'title'            => 'Edit RSS',
        'page callback'    => 'drupal_get_form',
        'page arguments'   => array('rss_mod_form', 4),
        'access arguments' => array('administer site configuration'),
        'type'             => MENU_CALLBACK,
    );

    // modrss delete
    $items['admin/config/content/rss_mod/%modrss/delete'] = array(
        'title'            => 'Delete RSS',
        'page callback'    => 'rss_mod_delete',
        'page arguments'   => array(4),
        'access arguments' => array('administer site configuration'),
        'type'             => MENU_CALLBACK,
    );
                                                                        /******--------******/
    $items['rss_mod'] = array(
        'title'            => 'RSS',
        'page callback'    => 'rss_mod_page',
        'access arguments' => array('access content'),
    );

    $items['rss_mod/%modrss/items'] = array(
        'title'            => 'RSS module content',
        'page callback'    => 'rss_content',
        'page arguments'   => array(1),
        'access callback'  => TRUE,
        'access arguments' => array('access content'),
        'type'             => MENU_CALLBACK,
    );


    return $items;
}

/******Далее мы опишем форму, через которую мы будем добавлять и редактировать наши RSS-ленты:*******/
function rss_mod_form($form, &$form_state, $rss = null)
{
    $form['name'] = array(
        '#title'         => t('RSS module name.'),
        '#description'   => t('Insert RSS name'),
        '#type'          => 'textfield',
        '#default_value' => $rss ? $rss['name'] : '',
        '#required'      => true,
    );

    $form['url'] = array(
        '#title'         => t('RSS url.'),
        '#description'   => t('Insert RSS url'),
        '#type'          => 'textfield',
        '#default_value' => $rss ? $rss['url'] : '',
        '#required'      => true,
    );

    $form['submit'] = array(
        '#type'  => 'submit',
        '#value' => $rss ? t('Save') : t('Add'),
    );

    if ($rss) {
        $form['id'] = array(
            '#type'  => 'value',
            '#value' => $rss['id'],
        );
    }

    return $form;
}

/*****Далее необходимо описать hook_form_validate(), который будет обрабатывать данные, введенные в форму:**/
function rss_mod_form_validate($form, &$form_state)
{
    $url = $form_state['values']['url'];

    if (fopen($url, "r")) {
        libxml_use_internal_errors(true);
        $rss_mod = simplexml_load_file($url);
        if (empty($rss_mod)) {
            form_set_error('url', t('URL is invalid!'));
        }
    } else {
        form_set_error('url', t('URL is invalid!'));
    }
}

/********Когда форма проходит валидацию, вызывается hook_form_submit():***********/
function rss_mod_form_submit($form, &$form_state)
{
    $rss = array(
        'name'       => $form_state['values']['name'],
        'url'        => $form_state['values']['url'],
        'created_at' => time(),
        'updated_at' => time(),
    );

    // save edit data
    if (isset($form_state['values']['id'])) {
        $rss['id'] = $form_state['values']['id'];
        drupal_write_record('rssmod', $rss, 'id');
        drupal_set_message(t('RSS Feed saved!'));
    } // add new data
    else {
        drupal_write_record('rssmod', $rss);
        drupal_set_message(t('RSS added!'));
    }

    drupal_goto('admin/config/content/rss_mod');
}
/*****Для того чтобы форма принимала не просто ID ленты ($modrss), а ее данные, нужно определить hool_load():***/
function rss_load($id)
{
    $rss = db_select('rssmod', 'n')
        ->fields('n', array('id', 'name', 'url', 'created_at', 'updated_at'))
        ->condition('n.id', $id)
        ->execute()->fetchAssoc();

    return $rss;
}
/******Далее функцию вывода страницы, на которой редактирование нашей таблицы RSS лент - rss_list():*****/
function rss_list()
{
    $header = array(
        array('data' => t('Name')),
        array('data' => t('URL')),
        array('data' => t('Actions'))
    );
    $rss = db_select('rssmod', 'n')
        ->fields('n', array('id', 'name', 'url'))
        ->execute()->fetchAll();
    $row = array();
    if ($rss) {
        foreach ($rss as $rss_mod) {
            $actions = array(
                l(t('edit'), 'admin/config/content/rss_mod/' . $rss_mod->id . '/edit'),
                l(t('delete'), 'admin/config/content/rss_mod/' . $rss_mod->id . '/delete'),
            );

            $row [] = array(
                array('data' => $rss_mod->name),
                array('data' => $rss_mod->url),
                array('data' => implode(' | ', $actions)),
            );
        }
    }

    return theme('table', array(
        'header' => $header,
        'rows'   => $row,
    ));
}
/***************функцию удаления записей rss_feeds_delete():*************/
function rss_mod_delete($rss)
{
    $rss_deleted = db_delete('rssmod')
        ->condition('id', $rss['id'])
        ->execute();
    drupal_set_message(t('RSS deleted!'));
    drupal_goto('admin/config/content/rss_mod');
}
/*******************/
function rss_contents($display)
{
    $query = db_select('rssmod', 'n')
        ->fields('n', array('id', 'name', 'url'))
        ->orderBy('name', 'DESC');

   /* if ($display == 'block') {*/
        $query->range(0, 5);
    /*}*/

    return $query->execute();
}
/******************* хук вывода блока — hook_block_view():*******************/
function rss_mod_block_view($delta = '')
{
    $blocks = array();
    switch ($delta) {
        case 'rss_mod':
            $select = db_select('rssmod', 'tc');
            $select->addField('tc', 'name');
            $select->addField('tc', 'url');

            $entries = $select->execute()->fetchAll();

            $blocks['subject'] = t('List of URLs');
            $blocks['content'] = theme('rssmod_block', array('urls' => $entries));
    }

    return $blocks;
}
/**********функцию отображения страницы, на которой будет список лент, *********/
function rss_mod_page()
{
    drupal_set_title(t('RSS'));

    $result = rss_contents('page')->fetchAll();

    if (!$result) {
        $page_array['rss_mod_arguments'] = array(
            '#title'  => t('RSS Module page'),
            '#markup' => t('No RSS feeds available'),
        );

        return $page_array;
    } else {
        $page_array = theme('rssmod_page', array('urls' => $result));

        return $page_array;
    }
}
/****************** страницу отображения контента:***********/
function rss_content($rss)
{
    $url = $rss['url'];

    libxml_use_internal_errors(true);
    $rss_mod = simplexml_load_file($url);
    if (!empty($rss_mod)) {
        drupal_set_title($rss_mod->channel->title);
        $page_array = theme('rssmod_content', array('items' => $rss_mod));

        return $page_array;
    } else {
        $page_array['rss_mod_arguments'] = array(
            '#title'  => t('All posts from the last week'),
            '#markup' => t('No posts available.'),
        );

        return $page_array;
    }
}


function rss_mod_theme()
{
    return array(
        'rssmod_block'   => array(
            'variables' => array(
                'urls' => NULL
            ),
            'template'  => 'rssmod-block',
        ),
        'rssmod_page'    => array(
            'variables' => array(
                'urls' => NULL
            ),
            'template'  => 'rssmod-page',
        ),
        'rssmod_content' => array(
            'variables' => array(
                'items' => NULL
            ),
            'template'  => 'rssmod-content',
        )
    );
}
